# ==============================================================================
# PIPELINE CONFIGURATION FILE
# ==============================================================================

# Input File Paths
metadata_file: "data/example/metadata.txt"
counts_matrix_file: "data/example/counts.txt"
qc_variables:
- "genotype"
- "condition"
color_variables:
  condition:
    ABA: "#91F2E2"
    Control: "#A8B2C1"
  genotype:
    abi1: "#D05A3F"
    wt: "#4A7C59"
group_variable: "condition"
formulas:
  "~ genotype":
    - "wt - abi1"
  "~ condition":
    - "Control - ABA"
  "~ condition + genotype":
    - "Control - ABA"
  "~ condition * genotype":
    - "Control_wt - Control_abi1"
    - "( Control_wt - Control_abi1 ) - ( ABA_wt - ABA_abi1 )"
